apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: {{ .Values.externalSecrets.namespace }}
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    name: {{ .Values.externalSecrets.name }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.secretKeys }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .remoteKey }}
  {{- end }}