apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080