apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: default
  labels:
    app: springboot-app
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

