env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: DATABASE_URL
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: DATABASE_PASSWORD
  - name: MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MAIL_USERNAME
  - name: MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MAIL_PASSWORD
